### ISSUE TITLE
166 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by anhnt92** [sdkbox/sdkbox-facebook-sample#2]
Hi, when build my game project with sdkbox facebook plugin, i get an error  166 duplicate symbols for architecture x86_64 such as duplicate symbol _llvm.cmdline in:
    /path/cpp/proj.ios_mac/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKAppEvents.o)

**Comment by darkdukey** [comment]
What other plugins are you using in your project?

**Comment by darkdukey** [comment]
Closing due to not able to reproduce
