### ISSUE TITLE
Test  iOS-CPP

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-facebook-sample#4]
以下为 facebook ios cpp 的测试结果

### Login

弹出登录页面

### check status

输出 permission list | access token | user id | FBSDK version

### requestReadPermission

弹窗确认获取读取权限

### requestPublishPermisson

弹窗确认获取发布权限

### capture screen

截取屏幕以用于分享

### share link

分享sdkbox至FB，登录 facebook 页面查看分享正常

### share photo

分享"capture screen"截取的屏幕至FB， 登录 facebook 页面查看分享正常

### dialog link

调用FB分享页面分享sdkbox

### dialog photo(on device)

模拟器测试提示错误

~~~
##FB onSharedFailed:{"message":"Feed share dialogs support FBSDKShareLinkContent.","code":2}
~~~

### onGetMyInfo

获取我的信息

~~~
##FB onGetMyInfo
##FB onAPI: tag -> me, json -> {"name":"Will Amigegjcjhhj Riceberg","id":"119572038378030","__debug__":{},"api":"me"}
~~~

### onGetMyFriends 

无法获取好友链

输出了 ##FB onGetMyFriends 无后序

### invite friends

邀请好友页面正常显示，发送好友邀请过程正常，无法确定对方是否收到邀请。

**Comment by darkdukey** [comment]
Missing  App Link URL已修复
