### ISSUE TITLE
Test  Android-CPP

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-facebook-sample#6]
以下为 facebook android cpp 的测试结果

### Login

弹出登录页面

### check status

输出 permission list | access token | user id | FBSDK version

### requestReadPermission

弹窗确认获取读取权限

### requestPublishPermisson

弹窗确认获取发布权限

### capture screen

截取屏幕以用于分享

### share link

分享sdkbox至FB，登录 facebook 页面查看分享正常

### share photo

分享"capture screen"截取的屏幕至FB， 登录 facebook 页面查看分享正常

### dialog link

调用FB分享页面分享sdkbox

### dialog photo(on device)

点击提示分享失败，需要安装 FB app 。最新版本的 FB app 仅支持安卓4.4以上，测试机为4.1，安装老版本 FB app 登录时异常，新版本 FB app 待测试。

### onGetMyInfo

获取我的信息

~~~
##FB onAPI: tag -> me, json -> {"id":"119572038378030","__debug__":{},"name":"Will Amigegjcjhhj Riceberg"}
~~~

### onGetMyFriends 

无法获取好友链

输出了 ##FB onGetMyFriends 无后序

### invite friends

邀请好友页面正常显示，发送好友邀请过程正常，无法确定对方是否收到邀请。

**Comment by darkdukey** [comment]
Missing App Link URL 已修复
