### ISSUE TITLE
Test  Android-JS

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-facebook-sample#8]
以下为 facebook android js 的测试结果

### Login

弹出登录页面

### Logout

注销账户

### check status

输出 isLogin | userid | permission |

### Read Perm

弹窗确认获取读取权限

### Write Perm

弹窗确认获取发布权限

### share link

分享sdkbox至FB，登录 facebook 页面查看分享正常

### dialog link

调用FB分享页面分享sdkbox，登录 facebook 页面查看分享正常

### Invite

邀请好友页面正常显示，发送好友邀请过程正常，无法确定对方是否收到邀请。

**Comment by darkdukey** [comment]
Missing App Link 已修复，请验证
